Repository hawks-atlanta/authentication-go, pull requests merged in 2023-10, with the labels that each got.

#43 Feat/logs
  controller/controller.go
  controller/log.go
  controller/log_test.go
  docs/spec.openapi.yaml
  go.mod
  go.sum
  internal/utils/ipaddr/ipaddr.go
  internal/utils/ipaddr/ipaddr_test.go
  models/log.go
  models/log_test.go
  models/user.go
  router/challenge.go
  router/log.go
  router/log_test.go
  router/login.go
  router/query.go
  router/register.go
  router/router.go
  router/update_password.go
  router/utils.go
Labels: documentation, feature

#44 chore: release v0.0.26
  CHANGELOG.md
  controller/controller.go
  controller/log.go
  controller/log_test.go
  docs/spec.openapi.yaml
  go.mod
  go.sum
  internal/utils/ipaddr/ipaddr.go
  internal/utils/ipaddr/ipaddr_test.go
  models/log.go
  models/log_test.go
  models/user.go
  package-lock.json
  package.json
  router/challenge.go
  router/log.go
  router/log_test.go
  router/login.go
  router/query.go
  router/register.go
  router/router.go
  router/update_password.go
  router/utils.go
Labels: feature

#46 docs(openapi): Fix indentation
  docs/spec.openapi.yaml
Labels: bug, documentation

#53 feat: added `/user/username`
  CHANGELOG.md
  controller/query.go
  controller/query_test.go
  docs/spec.openapi.yaml
  package-lock.json
  package.json
  router/query.go
  router/query_test.go
  router/router.go
  router/utils.go
Labels: documentation, feature
